{{- if .Values.secrets.enabled }}
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: ricardoplaza-service
spec:
  backendType: secretsManager
  # optional: specify role to assume when retrieving the data
  auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.secrets.serviceAccount }}
  data:
    {{- with .Values.secrets.data }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}