{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.secrets.serviceAccount }}
  labels:
    {{- include "ricardoplaza.labels" . | nindent 4 }}
  annotations:
     eks.amazonaws.com/role-arn: {{ .Values.secrets.roleArn }}
{{- end }}
